-- MySQL Script generated by MySQL Workbench
-- Thu Jun 22 11:00:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema inventory
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `inventory` ;

-- -----------------------------------------------------
-- Schema inventory
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventory` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `inventory` ;

-- -----------------------------------------------------
-- Table `inventory`.`__efmigrationshistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventory`.`__efmigrationshistory` ;

CREATE TABLE IF NOT EXISTS `inventory`.`__efmigrationshistory` (
  `MigrationId` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ProductVersion` VARCHAR(32) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`MigrationId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventory`.`warehouse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventory`.`warehouse` ;

CREATE TABLE IF NOT EXISTS `inventory`.`warehouse` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventory`.`addressing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventory`.`addressing` ;

CREATE TABLE IF NOT EXISTS `inventory`.`addressing` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `WarehouseId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Addressing_WarehouseId` (`WarehouseId` ASC) VISIBLE,
  CONSTRAINT `FK_Addressing_Warehouse_WarehouseId`
    FOREIGN KEY (`WarehouseId`)
    REFERENCES `inventory`.`warehouse` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 121
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventory`.`inventorystart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventory`.`inventorystart` ;

CREATE TABLE IF NOT EXISTS `inventory`.`inventorystart` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `InventoryStartDate` DATETIME(6) NOT NULL,
  `StockTakingFinishDate` DATETIME(6) NOT NULL,
  `IsCompleted` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventory`.`addressingsinventorystart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventory`.`addressingsinventorystart` ;

CREATE TABLE IF NOT EXISTS `inventory`.`addressingsinventorystart` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `AddressingId` INT NOT NULL,
  `InventoryStartId` INT NOT NULL,
  `AddressingCountRealized` TINYINT(1) NOT NULL,
  `AddressingCountEnded` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_AddressingsInventoryStart_AddressingId` (`AddressingId` ASC) VISIBLE,
  INDEX `IX_AddressingsInventoryStart_InventoryStartId` (`InventoryStartId` ASC) VISIBLE,
  CONSTRAINT `FK_AddressingsInventoryStart_Addressing_AddressingId`
    FOREIGN KEY (`AddressingId`)
    REFERENCES `inventory`.`addressing` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_AddressingsInventoryStart_InventoryStart_InventoryStartId`
    FOREIGN KEY (`InventoryStartId`)
    REFERENCES `inventory`.`inventorystart` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventory`.`aspnetroles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventory`.`aspnetroles` ;

CREATE TABLE IF NOT EXISTS `inventory`.`aspnetroles` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `NormalizedName` VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ConcurrencyStamp` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `RoleNameIndex` (`NormalizedName` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventory`.`aspnetroleclaims`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventory`.`aspnetroleclaims` ;

CREATE TABLE IF NOT EXISTS `inventory`.`aspnetroleclaims` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `RoleId` INT NOT NULL,
  `ClaimType` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ClaimValue` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_AspNetRoleClaims_RoleId` (`RoleId` ASC) VISIBLE,
  CONSTRAINT `FK_AspNetRoleClaims_AspNetRoles_RoleId`
    FOREIGN KEY (`RoleId`)
    REFERENCES `inventory`.`aspnetroles` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventory`.`aspnetusers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventory`.`aspnetusers` ;

CREATE TABLE IF NOT EXISTS `inventory`.`aspnetusers` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(80) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `Available` TINYINT(1) NOT NULL,
  `UserName` VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `NormalizedUserName` VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Email` VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `NormalizedEmail` VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `EmailConfirmed` TINYINT(1) NOT NULL,
  `PasswordHash` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `SecurityStamp` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ConcurrencyStamp` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `PhoneNumber` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `PhoneNumberConfirmed` TINYINT(1) NOT NULL,
  `TwoFactorEnabled` TINYINT(1) NOT NULL,
  `LockoutEnd` DATETIME(6) NULL DEFAULT NULL,
  `LockoutEnabled` TINYINT(1) NOT NULL,
  `AccessFailedCount` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `UserNameIndex` (`NormalizedUserName` ASC) VISIBLE,
  INDEX `EmailIndex` (`NormalizedEmail` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventory`.`aspnetuserclaims`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventory`.`aspnetuserclaims` ;

CREATE TABLE IF NOT EXISTS `inventory`.`aspnetuserclaims` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `UserId` INT NOT NULL,
  `ClaimType` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ClaimValue` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_AspNetUserClaims_UserId` (`UserId` ASC) VISIBLE,
  CONSTRAINT `FK_AspNetUserClaims_AspNetUsers_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `inventory`.`aspnetusers` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventory`.`aspnetuserlogins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventory`.`aspnetuserlogins` ;

CREATE TABLE IF NOT EXISTS `inventory`.`aspnetuserlogins` (
  `LoginProvider` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ProviderKey` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ProviderDisplayName` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `UserId` INT NOT NULL,
  PRIMARY KEY (`LoginProvider`, `ProviderKey`),
  INDEX `IX_AspNetUserLogins_UserId` (`UserId` ASC) VISIBLE,
  CONSTRAINT `FK_AspNetUserLogins_AspNetUsers_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `inventory`.`aspnetusers` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventory`.`aspnetuserroles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventory`.`aspnetuserroles` ;

CREATE TABLE IF NOT EXISTS `inventory`.`aspnetuserroles` (
  `UserId` INT NOT NULL,
  `RoleId` INT NOT NULL,
  `Discriminator` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`UserId`, `RoleId`),
  INDEX `IX_AspNetUserRoles_RoleId` (`RoleId` ASC) VISIBLE,
  CONSTRAINT `FK_AspNetUserRoles_AspNetRoles_RoleId`
    FOREIGN KEY (`RoleId`)
    REFERENCES `inventory`.`aspnetroles` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_AspNetUserRoles_AspNetUsers_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `inventory`.`aspnetusers` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventory`.`aspnetusertokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventory`.`aspnetusertokens` ;

CREATE TABLE IF NOT EXISTS `inventory`.`aspnetusertokens` (
  `UserId` INT NOT NULL,
  `LoginProvider` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `Name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `Value` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`UserId`, `LoginProvider`, `Name`),
  CONSTRAINT `FK_AspNetUserTokens_AspNetUsers_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `inventory`.`aspnetusers` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventory`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventory`.`item` ;

CREATE TABLE IF NOT EXISTS `inventory`.`item` (
  `Id` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `Name` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `UnitOfMeasurement` INT NOT NULL,
  `Quantity` DECIMAL(65,30) NOT NULL,
  `Observation` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ImageUrl` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventory`.`inventorymovement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventory`.`inventorymovement` ;

CREATE TABLE IF NOT EXISTS `inventory`.`inventorymovement` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `ItemId` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `MovementeType` INT NOT NULL,
  `WarehouseId` INT NOT NULL,
  `Amount` DOUBLE NOT NULL,
  `MovementDate` DATETIME(6) NOT NULL,
  `ImportDate` DATETIME(6) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_InventoryMovement_ItemId` (`ItemId` ASC) VISIBLE,
  INDEX `IX_InventoryMovement_WarehouseId` (`WarehouseId` ASC) VISIBLE,
  CONSTRAINT `FK_InventoryMovement_Item_ItemId`
    FOREIGN KEY (`ItemId`)
    REFERENCES `inventory`.`item` (`Id`),
  CONSTRAINT `FK_InventoryMovement_Warehouse_WarehouseId`
    FOREIGN KEY (`WarehouseId`)
    REFERENCES `inventory`.`warehouse` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventory`.`itemsaddressing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventory`.`itemsaddressing` ;

CREATE TABLE IF NOT EXISTS `inventory`.`itemsaddressing` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `AddressingId` INT NOT NULL,
  `ItemId` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_ItemsAddressing_AddressingId` (`AddressingId` ASC) VISIBLE,
  INDEX `IX_ItemsAddressing_ItemId` (`ItemId` ASC) VISIBLE,
  CONSTRAINT `FK_ItemsAddressing_Addressing_AddressingId`
    FOREIGN KEY (`AddressingId`)
    REFERENCES `inventory`.`addressing` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_ItemsAddressing_Item_ItemId`
    FOREIGN KEY (`ItemId`)
    REFERENCES `inventory`.`item` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 351
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventory`.`itemsstocktaking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventory`.`itemsstocktaking` ;

CREATE TABLE IF NOT EXISTS `inventory`.`itemsstocktaking` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `ItemId` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `InventoryStartId` INT NOT NULL,
  `ItemCountRealized` TINYINT(1) NOT NULL,
  `ItemCountEnded` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_ItemsStockTaking_InventoryStartId` (`InventoryStartId` ASC) VISIBLE,
  INDEX `IX_ItemsStockTaking_ItemId` (`ItemId` ASC) VISIBLE,
  CONSTRAINT `FK_ItemsStockTaking_InventoryStart_InventoryStartId`
    FOREIGN KEY (`InventoryStartId`)
    REFERENCES `inventory`.`inventorystart` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_ItemsStockTaking_Item_ItemId`
    FOREIGN KEY (`ItemId`)
    REFERENCES `inventory`.`item` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventory`.`stocktaking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventory`.`stocktaking` ;

CREATE TABLE IF NOT EXISTS `inventory`.`stocktaking` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `StockTakingDate` DATETIME(6) NULL DEFAULT NULL,
  `ItemId` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `AddressingsInventoryStartId` INT NOT NULL,
  `StockTakingQuantity` DECIMAL(65,30) NOT NULL,
  `FabricationDate` DATETIME(6) NULL DEFAULT NULL,
  `ExpirationDate` DATETIME(6) NULL DEFAULT NULL,
  `ItemBatch` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `StockTakingObservation` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `NumberOfCount` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_StockTaking_AddressingsInventoryStartId` (`AddressingsInventoryStartId` ASC) VISIBLE,
  INDEX `IX_StockTaking_ItemId` (`ItemId` ASC) VISIBLE,
  CONSTRAINT `FK_StockTaking_AddressingsInventoryStart_AddressingsInventorySt~`
    FOREIGN KEY (`AddressingsInventoryStartId`)
    REFERENCES `inventory`.`addressingsinventorystart` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_StockTaking_Item_ItemId`
    FOREIGN KEY (`ItemId`)
    REFERENCES `inventory`.`item` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
