insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (1, 'Shrimp - Tiger 21/25', 9, 44.27, 'Vivamus vestibulum sagittis sapien.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (2, 'Beef - Prime Rib Aaa', 6, 14.66, 'In sagittis dui vel nisl.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (3, 'Grouper - Fresh', 3, 97.87, 'Nulla ac enim.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (4, 'Soup - Knorr, Ministrone', 10, 20.73, 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (5, 'Tomato - Green', 11, 13.59, 'Curabitur at ipsum ac tellus semper interdum.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (6, 'Cheese - Mozzarella', 10, 46.93, 'Praesent lectus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (7, 'Apricots Fresh', 2, 77.35, 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (8, 'Wine - Pinot Noir Pond Haddock', 11, 98.42, 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (9, 'Tea - Lemon Scented', 5, 30.46, 'Cras non velit nec nisi vulputate nonummy.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (10, 'Food Colouring - Blue', 7, 16.58, 'Etiam justo.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (11, 'Crackers Cheez It', 3, 31.46, 'In eleifend quam a odio.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (12, 'Muffin Chocolate Individual Wrap', 0, 3.37, 'Aenean fermentum.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (13, 'Soup - Campbells', 1, 11.95, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (14, 'Smirnoff Green Apple Twist', 5, 83.16, 'In hac habitasse platea dictumst.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (15, 'Tomatoes - Orange', 0, 27.75, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (16, 'Wine - Duboeuf Beaujolais', 9, 85.04, 'Curabitur at ipsum ac tellus semper interdum.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (17, 'Plums - Red', 6, 39.81, 'Maecenas rhoncus aliquam lacus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (18, 'Wine - Niagara,vqa Reisling', 9, 85.58, 'Duis bibendum.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (19, 'Cake - French Pear Tart', 8, 76.09, 'Curabitur convallis.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (20, 'Muffin Batt - Ban Dream Zero', 1, 47.48, 'Nulla mollis molestie lorem.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (21, 'Water - Tonic', 2, 6.97, 'Sed ante.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (22, 'Pork - Sausage, Medium', 1, 97.11, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (23, 'Syrup - Monin - Granny Smith', 7, 58.75, 'Mauris lacinia sapien quis libero.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (24, 'Triple Sec - Mcguinness', 10, 69.83, 'Proin risus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (25, 'Asparagus - Mexican', 6, 50.43, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (26, 'Oil - Olive, Extra Virgin', 3, 42.06, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (27, 'Basil - Dry, Rubbed', 2, 1.57, 'In hac habitasse platea dictumst.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (28, 'Water - Spring Water 500ml', 0, 88.12, 'Sed accumsan felis.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (29, 'Wine - Red, Colio Cabernet', 4, 36.79, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (30, 'Cheese Cloth No 60', 2, 92.34, 'In quis justo.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (31, 'Cream - 10%', 3, 12.81, 'Aliquam quis turpis eget elit sodales scelerisque.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (32, 'Mushroom - King Eryingii', 10, 25.67, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (33, 'Crush - Orange, 355ml', 5, 5.63, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (34, 'Salmon - Sockeye Raw', 8, 28.78, 'Morbi a ipsum.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (35, 'Ecolab Digiclean Mild Fm', 4, 92.15, 'Vivamus in felis eu sapien cursus vestibulum.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (36, 'Appetizer - Mango Chevre', 2, 47.72, 'Mauris ullamcorper purus sit amet nulla.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (37, 'Salmon - Sockeye Raw', 10, 53.35, 'In hac habitasse platea dictumst.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (38, 'Sprouts - Alfalfa', 9, 20.87, 'Nullam varius.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (39, 'The Pop Shoppe Pinapple', 2, 54.09, 'Nunc nisl.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (40, 'Wine - Cabernet Sauvignon', 8, 62.26, 'Nam dui.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (41, 'Chinese Foods - Chicken Wing', 6, 79.54, 'Suspendisse accumsan tortor quis turpis.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (42, 'Mix - Cocktail Strawberry Daiquiri', 3, 45.05, 'Nunc nisl.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (43, 'Quail - Jumbo Boneless', 1, 31.03, 'Nunc purus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (44, 'Tart Shells - Savory, 4', 2, 54.57, 'Maecenas pulvinar lobortis est.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (45, 'Pasta - Elbows, Macaroni, Dry', 7, 78.62, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (46, 'Sultanas', 6, 74.13, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (47, 'Bulgar', 1, 63.22, 'Morbi vel lectus in quam fringilla rhoncus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (48, 'Cherries - Frozen', 3, 32.36, 'Mauris lacinia sapien quis libero.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (49, 'Pepper Squash', 10, 88.12, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (50, 'Pasta - Angel Hair', 6, 21.51, 'Curabitur in libero ut massa volutpat convallis.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (51, 'Lettuce - Escarole', 4, 67.53, 'Donec dapibus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (52, 'Quinoa', 1, 97.93, 'Etiam faucibus cursus urna.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (53, 'Table Cloth 62x120 White', 0, 12.22, 'Morbi non lectus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (54, 'Lettuce - Spring Mix', 7, 17.24, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (55, 'Bread - Calabrese Baguette', 8, 97.99, 'Praesent lectus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (56, 'Wine - Red, Gamay Noir', 11, 45.48, 'Phasellus id sapien in sapien iaculis congue.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (57, 'Soup - Campbells Beef Stew', 2, 25.17, 'Vivamus in felis eu sapien cursus vestibulum.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (58, 'Clam - Cherrystone', 11, 9.35, 'Aenean fermentum.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (59, 'Sauce Bbq Smokey', 10, 4.37, 'Phasellus id sapien in sapien iaculis congue.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (60, 'Greens Mustard', 9, 65.62, 'Donec dapibus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (61, 'Juice - Pineapple, 48 Oz', 1, 10.11, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (62, 'Cheese - Brie, Cups 125g', 3, 85.94, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (63, 'Fruit Salad Deluxe', 11, 39.39, 'Donec vitae nisi.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (64, 'Cocktail Napkin Blue', 0, 71.48, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (65, 'Green Scrubbie Pad H.duty', 6, 47.27, 'Quisque ut erat.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (66, 'Food Colouring - Blue', 11, 86.07, 'Morbi vel lectus in quam fringilla rhoncus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (67, 'Soup - Campbells Chili', 4, 18.52, 'In congue.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (68, 'Cake Circle, Foil, Scallop', 6, 24.28, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (69, 'Ginger - Pickled', 1, 86.61, 'Fusce posuere felis sed lacus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (70, 'Sausage - Andouille', 5, 9.78, 'In hac habitasse platea dictumst.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (71, 'Pork - Sausage, Medium', 10, 24.06, 'Maecenas tincidunt lacus at velit.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (72, 'Olives - Black, Pitted', 6, 38.5, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (73, 'Beer - True North Lager', 11, 61.72, 'Vivamus in felis eu sapien cursus vestibulum.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (74, 'Lamb Rack - Ontario', 3, 89.32, 'Donec dapibus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (75, 'Veal - Leg', 10, 68.9, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (76, 'Cookie Double Choco', 10, 37.78, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (77, 'Pate - Peppercorn', 0, 91.1, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (78, 'Iced Tea - Lemon, 460 Ml', 4, 21.91, 'Curabitur in libero ut massa volutpat convallis.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (79, 'Vector Energy Bar', 11, 45.79, 'Sed vel enim sit amet nunc viverra dapibus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (80, 'Yogurt - Plain', 3, 84.03, 'Morbi non quam nec dui luctus rutrum.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (81, 'Truffle - Whole Black Peeled', 10, 47.6, 'Aliquam quis turpis eget elit sodales scelerisque.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (82, 'Bay Leaf Fresh', 9, 86.05, 'Morbi vel lectus in quam fringilla rhoncus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (83, 'Container - Clear 16 Oz', 7, 7.83, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (84, 'Sultanas', 4, 28.69, 'Duis ac nibh.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (85, 'Wine - Sicilia Igt Nero Avola', 10, 56.54, 'Curabitur gravida nisi at nibh.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (86, 'Persimmons', 6, 56.05, 'Pellentesque ultrices mattis odio.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (87, 'Oil - Coconut', 11, 95.13, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (88, 'Mix - Cappucino Cocktail', 5, 67.39, 'Pellentesque ultrices mattis odio.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (89, 'Hipnotiq Liquor', 2, 3.56, 'Phasellus in felis.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (90, 'Roe - White Fish', 5, 90.69, 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (91, 'Longos - Grilled Chicken With', 3, 38.0, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (92, 'Beer - Steamwhistle', 1, 4.32, 'Proin at turpis a pede posuere nonummy.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (93, 'Kellogs Cereal In A Cup', 7, 9.27, 'Curabitur at ipsum ac tellus semper interdum.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (94, 'Sugar - Splenda Sweetener', 6, 35.51, 'Maecenas ut massa quis augue luctus tincidunt.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (95, 'Beans - Black Bean, Dry', 3, 2.41, 'Pellentesque at nulla.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (96, 'Vaccum Bag 10x13', 10, 76.67, 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (97, 'Cut Wakame - Hanawakaba', 1, 99.94, 'Proin risus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (98, 'Teriyaki Sauce', 3, 36.53, 'Maecenas pulvinar lobortis est.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (99, 'Sansho Powder', 4, 16.65, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (100, 'Cookie Dough - Oatmeal Rasin', 9, 60.08, 'In sagittis dui vel nisl.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (101, 'Soup - Campbells, Creamy', 3, 21.87, 'In blandit ultrices enim.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (102, 'Cheese - Mozzarella, Buffalo', 3, 18.21, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (103, 'Island Oasis - Ice Cream Mix', 4, 29.86, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (104, 'Nestea - Ice Tea, Diet', 11, 87.1, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (105, 'Energy Drink - Franks Pineapple', 10, 84.82, 'Nam tristique tortor eu pede.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (106, 'Veal - Loin', 8, 42.9, 'Suspendisse ornare consequat lectus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (107, 'Nantucket - Kiwi Berry Cktl.', 5, 16.61, 'Proin eu mi.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (108, 'Juice - Cranberry, 341 Ml', 5, 22.87, 'Vivamus in felis eu sapien cursus vestibulum.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (109, 'Puree - Raspberry', 5, 72.41, 'Sed accumsan felis.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (110, 'Pail - 15l White, With Handle', 10, 15.23, 'Integer tincidunt ante vel ipsum.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (111, 'Beans - Butter Lrg Lima', 8, 45.09, 'Vivamus in felis eu sapien cursus vestibulum.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (112, 'Jam - Apricot', 10, 84.58, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (113, 'Wine - Harrow Estates, Vidal', 9, 26.42, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (114, 'Pasta - Penne, Lisce, Dry', 2, 34.9, 'In hac habitasse platea dictumst.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (115, 'Wine - Conde De Valdemar', 10, 79.65, 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (116, 'Cups 10oz Trans', 8, 6.86, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (117, 'Tilapia - Fillets', 3, 23.64, 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (118, 'Schnappes Peppermint - Walker', 2, 51.57, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (119, 'Mushroom - King Eryingii', 2, 28.27, 'Vestibulum sed magna at nunc commodo placerat.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (120, 'Baking Powder', 8, 15.52, 'Duis aliquam convallis nunc.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (121, 'Pears - Fiorelle', 10, 3.62, 'Pellentesque at nulla.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (122, 'Munchies Honey Sweet Trail Mix', 1, 83.76, 'Vestibulum sed magna at nunc commodo placerat.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (123, 'Wine - Sauvignon Blanc', 6, 19.6, 'Proin risus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (124, 'Pork - Hock And Feet Attached', 2, 35.49, 'Nullam varius.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (125, 'Ham - Cooked Bayonne Tinned', 11, 57.36, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (126, 'Syrup - Kahlua Chocolate', 2, 44.05, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (127, 'Wine - Fino Tio Pepe Gonzalez', 8, 8.4, 'Praesent blandit lacinia erat.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (128, 'Octopus', 10, 21.63, 'In sagittis dui vel nisl.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (129, 'Red Currant Jelly', 0, 82.5, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (130, 'Cattail Hearts', 6, 16.39, 'Pellentesque at nulla.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (131, 'Arizona - Green Tea', 11, 44.97, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (132, 'Taro Root', 5, 71.22, 'Pellentesque eget nunc.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (133, 'Daikon Radish', 5, 45.24, 'Praesent blandit lacinia erat.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (134, 'Blueberries - Frozen', 6, 72.12, 'Morbi porttitor lorem id ligula.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (135, 'Lobster - Live', 9, 47.31, 'Ut at dolor quis odio consequat varius.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (136, 'Oil - Olive Bertolli', 0, 13.75, 'In quis justo.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (137, 'Energy Drink', 0, 55.98, 'Aenean sit amet justo.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (138, 'Flour Dark Rye', 7, 36.34, 'Phasellus sit amet erat.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (139, 'Wine - Spumante Bambino White', 0, 1.98, 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (140, 'Triple Sec - Mcguinness', 6, 62.29, 'Proin at turpis a pede posuere nonummy.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (141, 'Sauce - Demi Glace', 9, 52.68, 'Nam nulla.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (142, 'Roe - Flying Fish', 3, 29.34, 'Donec semper sapien a libero.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (143, 'Sauerkraut', 6, 64.03, 'Nam dui.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (144, 'Towels - Paper / Kraft', 7, 7.88, 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (145, 'Tea - Lemon Scented', 2, 77.91, 'Nulla tempus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (146, 'Edible Flower - Mixed', 4, 59.42, 'Morbi vel lectus in quam fringilla rhoncus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (147, 'Truffle Paste', 2, 22.3, 'Morbi non lectus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (148, 'Vodka - Moskovskaya', 1, 65.25, 'Cras in purus eu magna vulputate luctus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (149, 'Tea - Orange Pekoe', 2, 93.06, 'Duis aliquam convallis nunc.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (150, 'Longos - Burritos', 9, 47.32, 'Nulla suscipit ligula in lacus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (151, 'Sambuca - Ramazzotti', 4, 69.13, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (152, 'Cheese - Gorgonzola', 11, 90.61, 'Nullam molestie nibh in lectus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (153, 'Muffin Mix - Carrot', 5, 84.45, 'Quisque porta volutpat erat.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (154, 'Syrup - Monin - Granny Smith', 5, 38.55, 'Nulla tellus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (155, 'Zucchini - Mini, Green', 5, 19.1, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (156, 'Salmon - Atlantic, Skin On', 9, 2.4, 'Proin at turpis a pede posuere nonummy.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (157, 'Dish Towel', 6, 69.82, 'Suspendisse ornare consequat lectus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (158, 'Pail For Lid 1537', 0, 39.38, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (159, 'Ham - Black Forest', 5, 85.62, 'Nullam molestie nibh in lectus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (160, 'Water - Spring 1.5lit', 7, 77.95, 'Morbi porttitor lorem id ligula.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (161, 'Salmon - Whole, 4 - 6 Pounds', 6, 14.77, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (162, 'Longos - Chicken Curried', 10, 91.86, 'Proin risus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (163, 'Schnappes - Peach, Walkers', 2, 76.61, 'In sagittis dui vel nisl.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (164, 'Ginger - Fresh', 9, 57.37, 'Vivamus tortor.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (165, 'Spice - Paprika', 0, 84.66, 'In quis justo.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (166, 'Containter - 3oz Microwave Rect.', 0, 83.94, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (167, 'Compound - Rum', 4, 3.65, 'Etiam justo.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (168, 'Soup - Cream Of Broccoli, Dry', 11, 99.52, 'Aliquam quis turpis eget elit sodales scelerisque.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (169, 'Wine - Blue Nun Qualitatswein', 0, 81.71, 'Sed sagittis.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (170, 'Jolt Cola', 8, 51.78, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (171, 'Butter Ripple - Phillips', 11, 38.7, 'Praesent lectus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (172, 'Tea - Herbal I Love Lemon', 6, 99.64, 'Nullam varius.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (173, 'Nantucket - Kiwi Berry Cktl.', 8, 22.42, 'Integer non velit.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (174, 'Coffee Beans - Chocolate', 9, 8.27, 'Pellentesque at nulla.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (175, 'Truffle Cups - White Paper', 5, 12.52, 'Cras non velit nec nisi vulputate nonummy.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (176, 'Wood Chips - Regular', 9, 83.18, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (177, 'Juice - Orangina', 7, 95.07, 'Integer tincidunt ante vel ipsum.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (178, 'Barramundi', 1, 87.74, 'Nunc nisl.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (179, 'Beer - Camerons Auburn', 6, 45.92, 'Vestibulum sed magna at nunc commodo placerat.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (180, 'Vaccum Bag - 14x20', 9, 7.27, 'Curabitur in libero ut massa volutpat convallis.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (181, 'Sea Bass - Whole', 6, 67.21, 'Duis mattis egestas metus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (182, 'Coconut - Whole', 9, 9.25, 'In hac habitasse platea dictumst.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (183, 'Compound - Orange', 9, 81.43, 'Nulla ac enim.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (184, 'Iced Tea Concentrate', 3, 95.28, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (185, 'Wine - Tio Pepe Sherry Fino', 11, 30.82, 'Etiam vel augue.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (186, 'Pastry - Trippleberry Muffin - Mini', 6, 39.4, 'Cras in purus eu magna vulputate luctus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (187, 'Couscous', 6, 24.6, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (188, 'Wine - White, Riesling, Semi - Dry', 11, 53.97, 'Phasellus id sapien in sapien iaculis congue.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (189, 'Tomato Puree', 2, 84.25, 'Curabitur convallis.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (190, 'Wine - Peller Estates Late', 11, 43.34, 'Donec vitae nisi.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (191, 'Crush - Orange, 355ml', 6, 72.06, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (192, 'Shrimp - Prawn', 6, 24.51, 'Nam dui.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (193, 'Oranges - Navel, 72', 9, 17.61, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (194, 'Duck - Breast', 6, 22.71, 'Nam nulla.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (195, 'Beef - Tenderlion, Center Cut', 5, 16.9, 'Mauris lacinia sapien quis libero.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (196, 'Bouillion - Fish', 5, 97.39, 'Nunc nisl.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (197, 'Cabbage - Savoy', 8, 65.5, 'Nulla suscipit ligula in lacus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (198, 'Bread - Frozen Basket Variety', 4, 5.51, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (199, 'Lambcasing', 11, 99.56, 'Maecenas rhoncus aliquam lacus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (200, 'Wine - Duboeuf Beaujolais', 8, 87.98, 'Nulla justo.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (201, 'Cheese - Cheddar, Medium', 8, 4.38, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (202, 'Sauce - Gravy, Au Jus, Mix', 4, 67.2, 'Nulla justo.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (203, 'Clams - Bay', 0, 97.38, 'Duis at velit eu est congue elementum.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (204, 'Beef - Ground Medium', 5, 5.32, 'Donec ut dolor.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (205, 'Pear - Packum', 11, 94.24, 'Curabitur convallis.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (206, 'Flour - Semolina', 4, 79.03, 'Nulla tellus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (207, 'Extract - Almond', 1, 97.61, 'Aenean lectus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (208, 'Buffalo - Striploin', 10, 24.73, 'In quis justo.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (209, 'Artichoke - Bottom, Canned', 6, 40.07, 'Curabitur convallis.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (210, 'Beans - Soya Bean', 11, 72.06, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (211, 'Mushroom - Lg - Cello', 6, 9.96, 'Maecenas tincidunt lacus at velit.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (212, 'Silicone Paper 16.5x24', 7, 6.91, 'Duis consequat dui nec nisi volutpat eleifend.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (213, 'Pepper - Red Thai', 8, 17.45, 'Praesent lectus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (214, 'Mop Head - Cotton, 24 Oz', 3, 37.53, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (215, 'Steel Wool S.o.s', 0, 50.6, 'Donec posuere metus vitae ipsum.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (216, 'Lamb Leg - Bone - In Nz', 2, 87.0, 'Morbi non quam nec dui luctus rutrum.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (217, 'Table Cloth 62x114 White', 4, 76.63, 'Cras in purus eu magna vulputate luctus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (218, 'Amarula Cream', 1, 83.11, 'Nulla mollis molestie lorem.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (219, 'Beer - Blue', 9, 48.46, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (220, 'Corn Kernels - Frozen', 10, 37.54, 'Nulla ut erat id mauris vulputate elementum.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (221, 'Longos - Cheese Tortellini', 8, 89.02, 'Sed sagittis.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (222, 'Pasta - Bauletti, Chicken White', 3, 29.05, 'Aenean sit amet justo.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (223, 'Horseradish - Prepared', 11, 16.95, 'Duis at velit eu est congue elementum.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (224, 'Skirt - 24 Foot', 1, 13.22, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (225, 'Ginger - Crystalized', 10, 38.0, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (226, 'Baking Soda', 4, 91.23, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (227, 'Tumeric', 9, 98.79, 'Suspendisse ornare consequat lectus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (228, 'Chestnuts - Whole,canned', 8, 98.29, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (229, 'Cookie - Oreo 100x2', 8, 84.64, 'Phasellus sit amet erat.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (230, 'Marjoram - Dried, Rubbed', 2, 43.81, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (231, 'Island Oasis - Raspberry', 9, 10.19, 'Integer ac neque.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (232, 'Beer - Paulaner Hefeweisse', 4, 7.76, 'Etiam pretium iaculis justo.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (233, 'Table Cloth 72x144 White', 11, 18.02, 'Donec ut dolor.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (234, 'Black Currants', 0, 83.33, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (235, 'Macaroons - Two Bite Choc', 4, 32.05, 'Vestibulum rutrum rutrum neque.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (236, 'The Pop Shoppe - Lime Rickey', 5, 41.56, 'Praesent lectus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (237, 'Juice - Cranberry 284ml', 5, 48.44, 'Maecenas tincidunt lacus at velit.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (238, 'Sea Bass - Whole', 2, 70.6, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (239, 'Wine - Ruffino Chianti Classico', 10, 49.08, 'Integer non velit.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (240, 'Bread - Pain Au Liat X12', 0, 24.72, 'Proin eu mi.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (241, 'Salt - Rock, Course', 0, 1.87, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (242, 'Tea - English Breakfast', 11, 16.41, 'In congue.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (243, 'Lamb - Leg, Diced', 8, 79.99, 'Nulla suscipit ligula in lacus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (244, 'Tilapia - Fillets', 6, 59.7, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (245, 'Coffee - Cafe Moreno', 11, 53.11, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (246, 'Chicken Breast Halal', 5, 58.75, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (247, 'Sobe - Green Tea', 7, 23.05, 'Integer tincidunt ante vel ipsum.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (248, 'Gherkin', 11, 59.14, 'Etiam vel augue.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (249, 'Cup - 6oz, Foam', 10, 69.74, 'In blandit ultrices enim.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (250, 'Veal - Striploin', 11, 97.96, 'Phasellus sit amet erat.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (251, 'Wine - Riesling Alsace Ac 2001', 5, 39.43, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (252, 'Cheese - Brie, Triple Creme', 4, 69.47, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (253, 'Pork - Smoked Kassler', 1, 29.84, 'Integer non velit.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (254, 'Beef - Eye Of Round', 2, 16.06, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (255, 'Hot Choc Vending', 6, 6.66, 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (256, 'Bag Stand', 10, 72.83, 'Etiam pretium iaculis justo.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (257, 'Skirt - 24 Foot', 3, 83.97, 'Morbi quis tortor id nulla ultrices aliquet.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (258, 'Jello - Assorted', 4, 97.28, 'Duis at velit eu est congue elementum.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (259, 'Pepper - Black, Crushed', 7, 89.31, 'Quisque porta volutpat erat.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (260, 'Crab - Dungeness, Whole', 6, 96.28, 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (261, 'Lettuce - Escarole', 0, 2.78, 'Nunc nisl.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (262, 'Pepsi, 355 Ml', 8, 74.28, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (263, 'Sloe Gin - Mcguinness', 3, 9.24, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (264, 'Salsify, Organic', 9, 39.55, 'Suspendisse ornare consequat lectus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (265, 'Lettuce - Romaine', 7, 98.93, 'Praesent blandit.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (266, 'Wine - Alicanca Vinho Verde', 5, 71.69, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (267, 'Southern Comfort', 10, 44.12, 'Maecenas pulvinar lobortis est.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (268, 'Wine - Chardonnay Mondavi', 10, 6.5, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (269, 'Ham - Smoked, Bone - In', 6, 20.78, 'Mauris ullamcorper purus sit amet nulla.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (270, 'Onions - Cippolini', 10, 84.99, 'Nunc nisl.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (271, 'Longos - Lasagna Beef', 5, 30.0, 'Curabitur in libero ut massa volutpat convallis.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (272, 'Sauce - Hollandaise', 9, 69.53, 'Nunc purus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (273, 'Chinese Foods - Pepper Beef', 0, 93.09, 'Vivamus tortor.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (274, 'Wine - Pinot Noir Latour', 3, 4.78, 'Donec ut dolor.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (275, 'Flour - Corn, Fine', 11, 79.72, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (276, 'Wine - Pinot Grigio Collavini', 7, 23.97, 'Duis aliquam convallis nunc.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (277, 'Cheese - Blue', 1, 19.21, 'Aliquam erat volutpat.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (278, 'Orange Roughy 6/8 Oz', 7, 82.32, 'Maecenas tincidunt lacus at velit.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (279, 'Nutmeg - Ground', 7, 99.82, 'Curabitur gravida nisi at nibh.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (280, 'Butter - Salted, Micro', 2, 41.72, 'Nullam porttitor lacus at turpis.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (281, 'Ecolab - Medallion', 10, 16.91, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (282, 'Sauce - Caesar Dressing', 4, 89.78, 'In eleifend quam a odio.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (283, 'Wine - Magnotta - Cab Sauv', 9, 60.31, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (284, 'Pepper - Sorrano', 6, 41.09, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (285, 'Pork - Suckling Pig', 7, 63.19, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (286, 'Nut - Pecan, Pieces', 0, 71.12, 'Sed accumsan felis.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (287, 'Champagne - Brights, Dry', 4, 48.18, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (288, 'Onions Granulated', 7, 30.97, 'Vestibulum sed magna at nunc commodo placerat.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (289, 'Radish', 3, 32.35, 'Quisque porta volutpat erat.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (290, 'Oil - Sunflower', 5, 84.25, 'Nulla mollis molestie lorem.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (291, 'Vanilla Beans', 3, 23.42, 'Praesent id massa id nisl venenatis lacinia.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (292, 'Stock - Chicken, White', 4, 43.86, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (293, 'Table Cloth 53x69 White', 0, 45.0, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (294, 'Soup Campbells Beef With Veg', 1, 74.73, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (295, 'Puree - Passion Fruit', 7, 42.66, 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (296, 'Lemonade - Island Tea, 591 Ml', 4, 46.25, 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (297, 'Rosemary - Dry', 10, 82.66, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (298, 'Tuna - Canned, Flaked, Light', 2, 90.17, 'Duis ac nibh.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (299, 'Garlic - Peeled', 1, 63.07, 'Nunc nisl.');
insert into Item (id, Name, UnitOfMeasurement, Quantity, Observation) values (300, 'Island Oasis - Ice Cream Mix', 8, 42.52, 'Nullam varius.');
