insert into Warehouse (id, Name) values (1, 'Ratke LLC');
insert into Warehouse (id, Name) values (2, 'Lubowitz, Wisoky and Heaney');
insert into Warehouse (id, Name) values (3, 'Walsh, Labadie and Emard');
insert into Warehouse (id, Name) values (4, 'Kautzer Inc');
insert into Warehouse (id, Name) values (5, 'Sanford, Doyle and Hudson');
insert into Warehouse (id, Name) values (6, 'Dickinson, Daniel and Kassulke');
insert into Warehouse (id, Name) values (7, 'King, Considine and Kertzmann');
insert into Warehouse (id, Name) values (8, 'McDermott and Sons');
insert into Warehouse (id, Name) values (9, 'Simonis-Prohaska');
insert into Warehouse (id, Name) values (10, 'Weimann-Stroman');
